version: "3.9"

services:

  kafka:
    image: docker.io/bitnami/kafka:2
    ports:
        - "9092:9092"
    hostname: kafka
    volumes:
        - "kafka_data:/bitnami"
    environment:
        - KAFKA_ADVERTISED_HOST_NAME=kafka
        - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
        - ALLOW_PLAINTEXT_LISTENER=yes
        # username: user
        # password: bitnami
    depends_on:
        - zookeeper
  # For create event, attach console and run
  # /opt/bitnami/kafka/bin/kafka-console-producer.sh --topic my-first-topic --bootstrap-server localhost:9092
  # More info at https://kafka.apache.org/quickstart

  zookeeper:  
    image: docker.io/bitnami/zookeeper:3.7
    ports:
        - "2181:2181"
    volumes:
        - "zookeeper_data:/bitnami"
    environment:
        - ALLOW_ANONYMOUS_LOGIN=yes
  
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    restart: always
    ports:
        - "9000:8080"
    environment:
        KAFKA_CLUSTERS_0_NAME: local
        KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "kafka:9092"
    depends_on:
        - kafka

volumes:
   zookeeper_data:
      driver: local
   kafka_data:
      driver: local